### ISSUE TITLE
Allow users to specify the size of the file on the remote HTTPS server

### ISSUE THREAD

**Issue by teor2345** [pastly/simple-bw-scanner#124]
Following on from #123, I suggest we allow the following option:

> file_size: The size of the remote file, in bytes. sbws can measure relay speeds up to file_size / target_seconds. Faster relays will all have this maximum speed. (TODO: reword?) If not specified, defaults to 1 GB. (optional)

Then we don't have to upgrade the protocol to change the file size.

**Comment by pastly** [comment]
Sure, though maybe it should be renamed to `max_download_size` or something to that effect. We don't have to require the file to be of a very specific size. We just need to make sure it is at least as large as the largest download we are willing to make. Currently that's hardcoded because sbws scanner and server need to agree. But in the switch to HTTPS, we can make it a config with a sane default, like 1 GB.

**Comment by pastly** [comment]
@teor2345 I'm going to restate my idea for this issue more clearly. Please let me know what you think.

First add an option limiting the maximum download size sbws is willing to do.

```ini
[scanner]
# 1 GiB
max_download_size = 1073741824
```

Then mark a destination unusable if the file its URL points to is not large enough to handle the `max_download_size`

**Comment by teor2345** [comment]
I think max_download_size and min_download_size are fine.

I can see us setting min_download_size to (498 - protocol overhead) if we wanted to make sure small requests had a full cell.

See also my update to #125.
