### ISSUE TITLE
sbws should reset relay bandwidths when their IPv4 address changes

### ISSUE THREAD

**Issue by teor2345** [pastly/simple-bw-scanner#154]
This should be configurable by IP version.

At the moment, the defaults should be to reset on IPv4 change, but leave it alone on IPv6 change.

See trac 22308 for a similar issue with uptimes.

**Comment by pastly** [comment]
Let me know what you decide on implementing. I haven't worked on this because I didn't think it was actually necessary for the minimally viable product like its 1.0 milestone would suggest. But that doesn't mean in the last 5 minutes I haven't thought about this just enough to form an opinion on what the solution should look like ;)

**Comment by juga0** [comment]
i'll push to a branch, faster than explaining it.

Please, could you put in a milestone different to 1.0 all the tickets that you don't consider necessary for a MVP?.
Or the other way around,  put milestone 1.0 to tickets you would like to have for a MVP and/or let me know that all those that aren't in 1.0 are not intended for a MVP, and not that they're just forgotten
